services:
  postgres:
    image: postgres:17
    container_name: ibkr-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ibkr_trading
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
