"""Signal domain model representing a trading signal from strategy evaluation."""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class SignalType(Enum):
    """Type of trading signal generated by a strategy."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass(frozen=True)
class Signal:
    """A trading signal produced by strategy evaluation.

    Attributes:
        signal_type: The action indicated by the signal.
        timestamp: When the signal was generated.
        reason: Human-readable explanation of why the signal was generated.
    """

    signal_type: SignalType
    timestamp: datetime
    reason: str
